### ISSUE TITLE
Grant Type 설정

### ISSUE THREAD

**Issue by wonksing** [wonksing/oauth-server#12]
Grant Type 허용을 설정으로 처리하기, Implicit은 앞으로 영원히 쓰지 않을 거라 생각한다.
```go
func initServer(manager *manage.Manager) *server.Server {
	srv := server.NewDefaultServer(manager)
	srv.Config.AllowGetAccessRequest = true
	srv.SetAllowedGrantType(oauth2.AuthorizationCode, oauth2.ClientCredentials, oauth2.PasswordCredentials)
	return srv
}
```

**Comment by wonksing** [comment]
이렇게 설정
```yml
oauth:
  # allowed_grant_type: 'authorization_code,client_credentials,password,refresh_token'
  allowed_grant_type: 'authorization_code'
```
